GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3OTE5ODI1LCJpYXQiOjE3NDc5MTk1MjUsImp0aSI6IjcxZmFmZjg0NzBhNzQ0MThhMmRjY2FiMTA0Nzg1OWI5IiwidXNlcl9pZCI6MX0.1uYErE_-OuJWfN8nFvkLYBZI2aP56PJBxDNxzkw3k8Q

{
    "name": "New Product",
    "price": 19.99,
    "stock": 42,
    "description": "A new product description"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:8000/api/user-orders/ HTTP/1.1
Authorization: Bearer 